### ISSUE TITLE
artistic 2.0 license not recognized

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-input-eventlog#27]
```
1) Project licenses logstash-input-eventlog behaves like runtime license test has runtime dependencies with expected licenses
     Failure/Error: expect(license.downcase).to match(expected_licenses)
       expected "artistic 2.0" to match /(?-mix:mit)|(?-mix:apache*)|(?-mix:bsd)|(?-mix:ruby)|(?-mix:lgpl)/
       Diff:
       @@ -1,2 +1,2 @@
       -/(?-mix:mit)|(?-mix:apache*)|(?-mix:bsd)|(?-mix:ruby)|(?-mix:lgpl)/
       +"artistic 2.0"
     Shared Example Group: "runtime license test" called from ./spec/license_spec.rb:62
     # ./spec/license_spec.rb:50:in `(root)'
     # ./spec/license_spec.rb:49:in `(root)'
     # ./spec/license_spec.rb:46:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.7/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:42:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
```
